### ISSUE TITLE
добавить команду (или в имеющуюся команду) запись в енв MOONSHINE_ROUTE_PREFIX=admin

### ISSUE THREAD

**Issue by AlessandroBakh** [lee-to/moonshine-doc#178]
привет, я сделал всё по документации, а потом сидел и искал что же нужно сделать, чтобы у меня /admin появилось в пустом приложении, подумал может авторизацию нужно организовать самому, об этом ничего не было в документации,
потом в демо проекте увидел эту запись в env, у себя прописал и ура, я попал в админку

думаю будет круто, если на composer install будет добавляться эта запись или в какой-то стартовой команде, типа moonshine:init

**Comment by DissNik** [comment]
Добавлять запись в env не обязательно, данная настройка находится в конфигурационном файле. По умолчанию она имеет значение moonshine, но часто ее переопределяют на admin, это можно сделать как правкой конфига, так и внести запись в env.

Нужно будет добавить в документацию, что админ-панель доступна первоначально по адресу /moonshine, который можно изменить.
