### ISSUE TITLE
Ошибка в пути кастомных иконок

### ISSUE THREAD

**Issue by timurashurov12** [lee-to/moonshine-doc#395]
На странице https://moonshine-laravel.com/docs/resource/icons/icons#custom
<img width="1134" alt="Снимок экрана 2024-01-25 в 22 41 48" src="https://github.com/moonshine-software/doc/assets/56439783/728b0ac1-d2ad-4ef3-b52e-2cb49a9ecca4">

не верное описание, для создания пути иконок, иконки не находятся и moonshine начинает ругаться

resources/views/vendor/moonshine/ui/icons - вот это правильный путь

**Comment by DissNik** [comment]
Спасибо!
