### ISSUE TITLE
Table Кнопки

### ISSUE THREAD

**Issue by ArtemYurov** [lee-to/moonshine-doc#425]
https://moonshine-laravel.com/docs/resource/models-resources/resources-table#buttons

добавить в конце:

Для добавления кнопки в список перед таблицей (перед кнопкой Создать)
```
    public function actions(): array
    {
        return [
                    ActionButton::make('Link', '/endpoint'),
        ];
    }

```

**Comment by lee-to** [comment]
actions не имеют отношения к Table
