### ISSUE TITLE
Translatable

### ISSUE THREAD

**Issue by austyuzhaninov** [lee-to/moonshine-doc#52]
Добрый день, в документации админпанели есть поле Translatable которое зависит от пакета Spatie\Translatable и оформленно отдельным пакетом. На текущий момент пакет не доступен.

> composer require visual-ideas/moonshine-spatie-translatable

visual-ideas/moonshine-spatie-translatable отсутствует?

**Comment by alexvenga** [comment]
Пакет доступен и полностью работоспособен!
