### ISSUE TITLE
Добавить упоминание, что поля, участвующие в фильтрации, нужно добавить в свойство $fillable

### ISSUE THREAD

**Issue by shevl-dev** [lee-to/moonshine-doc#520]
https://moonshine-laravel.com/docs/resource/models-resources/resources-filters

**Comment by DissNik** [comment]
а разве есть массовое присвоение?

**Comment by shevl-dev** [comment]
> а разве есть массовое присвоение?

Не знаю как под капотом фильтры работают, но пока я не добавил поле в свойство $fillable, выбрасывалось соответствующее исключение при отправке запроса фильтрации:

![image](https://github.com/user-attachments/assets/19306657-61f5-4352-b282-360b3e21ad93)

**Comment by DissNik** [comment]
добавите?

**Comment by shevl-dev** [comment]
Да без проблем, писал чтобы удостовериться что я ничего не путаю, и чтобы не забыть )
