### ISSUE TITLE
Проблема с переключением языка

### ISSUE THREAD

**Issue by dragomano** [lee-to/moonshine-doc#578]
Если на главной странице документации несколько раз попереключать язык, переключение сломается, в адресной строке будет просто копиться параметр `_lang`:

`https://moonshine-laravel.com/docs?_lang=_lang=_lang=_lang=_lang=ru`

**Comment by lee-to** [comment]
А где именно переключать?

**Comment by dragomano** [comment]
Именно на главной странице `https://moonshine-laravel.com/docs`, несколько раз подряд, но сейчас я эту ошибку уже не наблюдаю :)

**Comment by lee-to** [comment]
Нашел в чем была проблема, спасибо!
