### ISSUE TITLE
Битая ссылка

### ISSUE THREAD

**Issue by Vladislav009** [lee-to/moonshine-doc#579]
Всем доброго времени суток. Обнаружил битую ссылку.
https://moonshine-laravel.com/ru/docs/3.x/fields/code#basics в данном разделе.
![image](https://github.com/user-attachments/assets/aeefb3d1-e93a-473a-9e77-c3e3c8f3b45e)

Сама ссылка - https://moonshine-laravel.com/screenshots/code.png

**Comment by lee-to** [comment]
Исправили, спасибо
