### ISSUE TITLE
Invalid link to Laravel documentation

### ISSUE THREAD

**Issue by shevl-dev** [lee-to/moonshine-doc#582]
В этом разделе документации в первом абзаце ссылка на раздел документации Laravel, но почему-то в ссылку подставляется суффикс 'ru', хотя в исходном тексте на гите этого нет, в итоге ссылка не работает:

https://moonshine-laravel.com/ru/docs/3.x/security/authorization

Думал исправлю сам, но исходная ссылка в файле authorization.md корректная, а почему подставляется 'ru' так и не понял...

**Comment by lee-to** [comment]
Fixed
