### ISSUE TITLE
Навигация по рецептам

### ISSUE THREAD

**Issue by shevl-dev** [lee-to/moonshine-doc#593]
А вот с этой навигацией нельзя что-нибудь придумать? Названия рецептов довольно длинные, не видно даже половину некоторых названий.

Возможно есть есть возможность:
- добавить title ссылкам, чтобы при наведении отображалось полное название;
- или сделать корневую страницу рецептов с полным списком.

В целом это касается всей навигации, но особенно заметно в рецептах.

![image](https://github.com/user-attachments/assets/f825086b-2fba-4b9b-a1ba-2df8566ac0b0)

**Comment by ArtemYurov** [comment]
до кучи и тут не совсем к месту обрезание
<img width="298" alt="image" src="https://github.com/user-attachments/assets/4f4a7056-f611-46ea-805d-b87af8416f5c" />

**Comment by shevl-dev** [comment]
> до кучи и тут не совсем к месту обрезание
> <img width="298" alt="image" src="https://github.com/user-attachments/assets/4f4a7056-f611-46ea-805d-b87af8416f5c" />
> 

Да это одно и тоже меню, я просто акцентировал на рецептах, потому что там таких разделов много

**Comment by lee-to** [comment]
А есть у вас идеи как нужно сделать? Лично я пока не знаю, ну только если делать заголовки короче

**Comment by ArtemYurov** [comment]
А если в 2 строчки сделать длинные названия?

**Comment by shevl-dev** [comment]
> А есть у вас идеи как нужно сделать? Лично я пока не знаю, ну только если делать заголовки короче

Я только хотел уточнить, возможно есть возможность добавить атрибут title, чтобы при наведении видеть полное название

**Comment by lee-to** [comment]
> > А есть у вас идеи как нужно сделать? Лично я пока не знаю, ну только если делать заголовки короче
> 
> Я только хотел уточнить, возможно есть возможность добавить атрибут title, чтобы при наведении видеть полное название

Да title там теперь есть и я добавил мета информацию
Вот пример https://github.com/moonshine-software/doc/blob/3.x/ru/upgrade-guide.md
Заголовок меню будет браться из тайтла

**Comment by lee-to** [comment]
Можете пройтись пофиксить там где большие заголовки
